version: "3"

services:
    attacker:
        image: ubuntu:21.10
        container_name: seed-attacker
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.9

    hostA:
        image: ubuntu:21.10
        container_name: hostA-10.9.0.5
        tty: true
        cap_add:
                - ALL
        volumes:
                - ./volumes:/volumes
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5
       

    hostB:
        image: ubuntu:21.10
        container_name: hostB-10.9.0.6
        tty: true
        cap_add:
                - ALL
        volumes: 
                - ./volumes:/volumes
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6
     
                  
networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

